# Stacey's Code for data clean up

In [1]:
#import dependencies

import pandas as pd
import os
import csv

In [2]:
# The path to our CSV file
file = "Resources/or_historical_wildfires.csv"

#Read data into csv
or_hist_df = pd.read_csv(file)
or_hist_df.head()

,id,fire_year,report_date,county,latitude,longitude,total_acres,odf_acres,fuel_model,fuel_descr,general_cause,fire_name,district,unit,legal
0,1,1961,1961-01-25,Washington,NaN,NaN,8.00,8.00,X,non-wildland fuel,Miscellaneous,61511004,51 - Tillamook,Tillamook,T000 R000 S00
1,2,1961,1961-04-04,Washington,NaN,NaN,5.00,5.00,X,non-wildland fuel,Debris Burning,61511009,51 - Tillamook,Tillamook,T000 R000 S00
2,3,1961,1961-04-09,Washington,NaN,NaN,0.05,0.05,X,non-wildland fuel,Recreationist,61511011,51 - Tillamook,Tillamook,T000 R000 S00
3,4,1961,1961-05-24,Washington,NaN,NaN,1.00,1.00,X,non-wildland fuel,Smoking,61511012,51 - Tillamook,Tillamook,T000 R000 S00
4,5,1961,1961-06-19,Washington,NaN,NaN,0.05,0.05,X,non-wildland fuel,Miscellaneous,61511016,51 - Tillamook,Tillamook,T000 R000 S00

In [3]:
#drop NAN values, we want to be able to plot with lat and lon
or_hist_df = or_hist_df.dropna(how='any')

In [4]:
or_hist_df.head()

,id,fire_year,report_date,county,latitude,longitude,total_acres,odf_acres,fuel_model,fuel_descr,general_cause,fire_name,district,unit,legal
48,49,1961,1961-01-26,Clatsop,46.104106,-122.172606,1.0,1.0,U,closed canopy pine,Debris Burning,61521006,52 - Astoria,Astoria,T07N R09W S08
51,52,1961,1961-07-11,Clatsop,46.148181,-122.110722,0.1,0.1,U,closed canopy pine,Equipment Use,61521027,52 - Astoria,Astoria,T08N R10W S26
52,53,1961,1961-07-11,Clatsop,46.075392,-122.295075,0.1,0.1,U,closed canopy pine,Equipment Use,61521028,52 - Astoria,Astoria,T07N R08W S20
56,57,1961,1961-08-08,Clatsop,46.177878,-122.401967,0.1,0.1,G,conifer old growth,Equipment Use,61521050,52 - Astoria,Astoria,T08N R07W S18
75,76,1961,1961-09-26,Clatsop,46.148189,-122.173517,0.1,0.1,G,conifer old growth,Juveniles,61521118,52 - Astoria,Astoria,T08N R09W S29

In [5]:
#drop fuel description that is less than one acre and isn't a wildland fuel
#index_names = or_hist_df[ (or_hist_df['total_acres'] <= .1) & (or_hist_df['fuel_descr'] == 'non-wildland fuel')].index
#or_hist_df.drop(index_names, inplace = True)
index_names2 = or_hist_df[ or_hist_df['county'] == "Other St." ].index
or_hist_df.drop(index_names2, inplace = True)
index_names3 = or_hist_df[ or_hist_df['total_acres'] <= 0].index
or_hist_df.drop(index_names3, inplace = True)

In [6]:
#grab 1975-80 and 2015-2021
options = [1975, 1976, 1977, 1978, 1979, 1980, 1981, 2015, 2016, 2017, 2018, 2019, 2020, 2021]
or_hist_df = or_hist_df.loc[or_hist_df['fire_year'].isin(options)]
  
or_hist_df

,id,fire_year,report_date,county,latitude,longitude,total_acres,odf_acres,fuel_model,fuel_descr,general_cause,fire_name,district,unit,legal
16174,16175,1976,1976-09-09,Tillamook,45.251897,-122.403356,1.00,1.00,R,hardwood summer,Debris Burning,76511236,51 - Tillamook,Tillamook,T04S R07W S06
16175,16176,1976,1976-09-09,Tillamook,45.266517,-122.165742,7.00,7.00,G,conifer old growth,Debris Burning,76511237,51 - Tillamook,Tillamook,T03S R09W S31
16178,16179,1976,1976-10-09,Tillamook,45.295022,-122.505725,1.00,1.00,G,conifer old growth,Debris Burning,76511261,51 - Tillamook,Tillamook,T03S R07W S24
16179,16180,1976,1976-10-18,Tillamook,45.682097,-122.346747,8.00,8.00,F,dense brush,Smoking,76511268,51 - Tillamook,Tillamook,T02N R08W S03
16180,16181,1976,1976-10-02,Tillamook,45.739472,-122.464664,834.00,834.00,F,dense brush,Recreationist,76511269,51 - Tillamook,Tillamook,T03N R07W S15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66284,66285,2020,2020-05-29,Klamath,43.429333,-120.503283,0.10,0.10,C,open pine grass under,Lightning,CB 17,99 - Walker Range,Walker FPA,T25S R10E S2 SESW
66296,66297,2020,2020-06-03,Klamath,43.503172,-120.363325,0.25,0.25,C,open pine grass under,Lightning,CB 7,99 - Walker Range,Walker FPA,T24S R9E S10 SWSE
66307,66308,2020,2020-06-23,Klamath,43.592750,-120.354250,2.00,2.00,X,non-wildland fuel,Arson,Processor,99 - Walker Range,Walker FPA,T23S R9E S9 NESE
66309,66310,2020,2020-06-30,Klamath,43.471200,-120.296167,0.10,0.10,X,non-wildland fuel,Equipment Use,Bark,99 - Walker Range,Walker FPA,T24S R9E S30 NWNW
66310,66311,2020,2020-06-30,Klamath,43.471200,-120.296167,0.10,0.10,X,non-wildland fuel,Equipment Use,Interfor,99 - Walker Range,Walker FPA,T24S R9E S30 NWNW

In [7]:
or_hist_df.head()

,id,fire_year,report_date,county,latitude,longitude,total_acres,odf_acres,fuel_model,fuel_descr,general_cause,fire_name,district,unit,legal
16174,16175,1976,1976-09-09,Tillamook,45.251897,-122.403356,1.0,1.0,R,hardwood summer,Debris Burning,76511236,51 - Tillamook,Tillamook,T04S R07W S06
16175,16176,1976,1976-09-09,Tillamook,45.266517,-122.165742,7.0,7.0,G,conifer old growth,Debris Burning,76511237,51 - Tillamook,Tillamook,T03S R09W S31
16178,16179,1976,1976-10-09,Tillamook,45.295022,-122.505725,1.0,1.0,G,conifer old growth,Debris Burning,76511261,51 - Tillamook,Tillamook,T03S R07W S24
16179,16180,1976,1976-10-18,Tillamook,45.682097,-122.346747,8.0,8.0,F,dense brush,Smoking,76511268,51 - Tillamook,Tillamook,T02N R08W S03
16180,16181,1976,1976-10-02,Tillamook,45.739472,-122.464664,834.0,834.0,F,dense brush,Recreationist,76511269,51 - Tillamook,Tillamook,T03N R07W S15

In [8]:
#grab columns we care about
or_hist_df = or_hist_df[['fire_year', 'report_date', 'county', 'latitude', 'longitude', 'total_acres', 'general_cause']]

In [9]:
#sort by report date
or_hist_df = or_hist_df.sort_values(by=['report_date'])

In [10]:
#reset index
or_hist_df = or_hist_df.reset_index(drop=True)
or_hist_df

,fire_year,report_date,county,latitude,longitude,total_acres,general_cause
0,1975,1975-03-27,Douglas,43.645967,-123.793036,9.00,Equipment Use
1,1975,1975-04-14,Linn,44.453025,-121.427158,1.00,Miscellaneous
2,1975,1975-04-28,Deschutes,44.087556,-120.626453,5.00,Recreationist
3,1975,1975-05-13,Klamath,43.580408,-120.425408,5.00,Debris Burning
4,1975,1975-05-13,Klamath,42.797525,-120.580886,116.00,Debris Burning
...,...,...,...,...,...,...,...
8892,2021,2021-05-21,Lane,44.200000,-123.900000,0.01,Debris Burning
8893,2021,2021-05-22,Hood River,45.576111,-120.532500,0.10,Recreationist
8894,2021,2021-05-23,Deschutes,43.665278,-120.487778,0.01,Equipment Use
8895,2021,2021-05-24,Wasco,45.265000,-120.767778,14.56,Debris Burning
8896,2021,2021-05-27,Columbia,45.841167,-121.141000,0.03,Debris Burning

In [11]:
or_hist_df.to_csv("Resources/or_df.csv")

1991    2029
1987    1631
1992    1617
1970    1412
1994    1403
2006    1243
2001    1239
1985    1219
1974    1150
2007    1150
1990    1145
2013    1144
1999    1132
1975    1132
2002    1125
1989    1114
2003    1101
1986    1100
1988    1096
1977    1072
2014    1070
2018    1069
1972    1040
2008    1030
2017    1026
2015    1021
1996    1006
2019     981
1980     960
1967     956
1995     954
1984     948
1973     942
2009     923
1998     921
2020     912
1979     903
1981     895
1978     871
2004     868
2000     866
1982     863
1976     827
1993     795
2016     783
1997     763
2005     762
1983     761
1968     685
1969     663
2011     657
2012     652
1971     634
2010     628
2021     185
1961       9
1964       5
1960       4
1962       3
1963       2
Name: fire_year, dtype: int64